version: '3'
services:
  paymentDB:
    image: postgres:15.1-alpine
    ports:
      - "5435:5432"
    container_name: paymentDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - paymentdb_data:/var/lib/postgresql/data
      - ./init-db/payment.sql:/docker-entrypoint-initdb.d/init.sql:ro

  statisticDB:
    image: postgres:15.1-alpine
    ports:
      - "5434:5432"
    container_name: statisticDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistic
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - statisticdb_data:/var/lib/postgresql/data
      - ./init-db/statistic.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  paymentdb_data:
  statisticdb_data: