spring:
  application.name: analyse-payment
  datasource:
    url: jdbc:postgresql://localhost:5434/statistic
    username: postgres
    password: password

debezium:
  target:
    hostname: localhost
    port: 5435
    dbname: payment
    username: postgres
    password: password

logging:
  level:
    ru.tbank.smartdata.analyse.payment.listener: TRACE
